import fs from 'fs';
import path from 'path';
import { fileURLToPath } from 'url';

const __filename = fileURLToPath(import.meta.url);
const __dirname = path.dirname(__filename);

function createRawRecord(id, name, provider, sourceFoodId, dataset, foodState, scientificName, category, subCategory, servingUnit, defaultServingGrams, nutrients, aliases, notes) {
  return {
    rawId: id,
    rawName: name,
    provider: provider,
    dataset: dataset,
    sourceFoodId: sourceFoodId,
    sourceReference: provider === 'IFCT_2017' ? 'ICMR-NIN Indian Food Composition Tables (IFCT 2017)' : 'USDA FoodData Central Foundation / SR Legacy',
    sourceVersion: provider === 'IFCT_2017' ? 'IFCT 2017 v1.0' : 'USDA FDC 2023',
    verified: true,
    foodState: foodState,
    scientificName: scientificName || null,
    category: category,
    subCategory: subCategory,
    servingUnit: servingUnit,
    defaultServingGrams: defaultServingGrams,
    aliases: aliases || [],
    nutrientsPer100g: nutrients,
    notes: notes || null
  };
}

function normalizeRecord(raw) {
  return {
    id: `food_${raw.provider.toLowerCase()}_${raw.sourceFoodId.toLowerCase()}`,
    name: raw.rawName,
    aliases: raw.aliases,
    category: raw.category,
    subCategory: raw.subCategory,
    foodState: raw.foodState,
    scientificName: raw.scientificName,
    servingUnit: raw.servingUnit,
    defaultServingGrams: raw.defaultServingGrams,
    nutritionPer100g: {
      energyKcal: raw.nutrientsPer100g.energyKcal ?? null,
      proteinG: raw.nutrientsPer100g.proteinG ?? null,
      carbohydratesG: raw.nutrientsPer100g.carbohydratesG ?? null,
      fatG: raw.nutrientsPer100g.fatG ?? null,
      fiberG: raw.nutrientsPer100g.fiberG ?? null,
      sugarG: raw.nutrientsPer100g.sugarG ?? null,
      sodiumMg: raw.nutrientsPer100g.sodiumMg ?? null,
      calciumMg: raw.nutrientsPer100g.calciumMg ?? null,
      ironMg: raw.nutrientsPer100g.ironMg ?? null,
      potassiumMg: raw.nutrientsPer100g.potassiumMg ?? null,
      vitaminAMcg: raw.nutrientsPer100g.vitaminAMcg ?? null,
      vitaminCMg: raw.nutrientsPer100g.vitaminCMg ?? null,
      vitaminDMcg: raw.nutrientsPer100g.vitaminDMcg ?? null,
      vitaminB12Mcg: raw.nutrientsPer100g.vitaminB12Mcg ?? null,
      folateMcg: raw.nutrientsPer100g.folateMcg ?? null
    },
    source: {
      provider: raw.provider,
      dataset: raw.dataset,
      sourceFoodId: raw.sourceFoodId,
      sourceReference: raw.sourceReference,
      sourceVersion: raw.sourceVersion,
      verified: raw.verified
    },
    notes: raw.notes
  };
}

const rawList = [];

// 1. RICE & GRAINS (13)
rawList.push(createRawRecord('A001', 'Rice, raw, milled', 'IFCT_2017', 'A001', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Oryza sativa', 'rice_grains', 'milled_rice', 'cup', 150, { energyKcal: 345, proteinG: 6.8, carbohydratesG: 78.2, fatG: 0.5, fiberG: 0.6, sugarG: 0.1, sodiumMg: 5.0, calciumMg: 10.0, ironMg: 0.7, potassiumMg: 95.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 8.0 }, ['Arisi', 'Chawal', 'Raw Milled Rice'], 'Standard polished raw rice used across South India.'));
rawList.push(createRawRecord('A002', 'Parboiled rice, raw', 'IFCT_2017', 'A002', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Oryza sativa', 'rice_grains', 'parboiled_rice', 'cup', 150, { energyKcal: 349, proteinG: 7.2, carbohydratesG: 77.4, fatG: 0.4, fiberG: 0.9, sugarG: 0.1, sodiumMg: 6.0, calciumMg: 12.0, ironMg: 1.1, potassiumMg: 110.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 11.0 }, ['Puzhungal Arisi', 'Usna Chawal'], 'Steam parboiled rice commonly used for South Indian lunch rice.'));
rawList.push(createRawRecord('A003', 'Brown rice, raw', 'IFCT_2017', 'A003', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Oryza sativa', 'rice_grains', 'whole_grain_rice', 'cup', 150, { energyKcal: 353, proteinG: 7.5, carbohydratesG: 74.0, fatG: 2.7, fiberG: 3.5, sugarG: 0.7, sodiumMg: 7.0, calciumMg: 23.0, ironMg: 1.8, potassiumMg: 223.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 20.0 }, ['Kai Kuthal Arisi', 'Unpolished Rice'], 'Whole unpolished brown grain rice high in dietary fiber.'));
rawList.push(createRawRecord('A004', 'Basmati rice, raw', 'IFCT_2017', 'A004', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Oryza sativa', 'rice_grains', 'aromatic_rice', 'cup', 150, { energyKcal: 347, proteinG: 7.9, carbohydratesG: 77.1, fatG: 0.6, fiberG: 0.8, sugarG: 0.1, sodiumMg: 4.0, calciumMg: 9.0, ironMg: 0.8, potassiumMg: 105.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 9.0 }, ['Long grain rice', 'Biryani Rice'], 'Long grain aromatic rice.'));
rawList.push(createRawRecord('A005', 'Idli rice, raw', 'IFCT_2017', 'A005', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Oryza sativa', 'rice_grains', 'short_grain_rice', 'cup', 150, { energyKcal: 346, proteinG: 6.9, carbohydratesG: 78.5, fatG: 0.5, fiberG: 0.5, sugarG: 0.1, sodiumMg: 5.0, calciumMg: 11.0, ironMg: 0.75, potassiumMg: 98.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 8.5 }, ['Idli Arisi', 'Short Grain Parboiled'], 'Short grain parboiled rice optimized for Idli and Dosa batter.'));
rawList.push(createRawRecord('A018', 'Wheat, whole, raw', 'IFCT_2017', 'A018', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Triticum aestivum', 'rice_grains', 'whole_wheat', 'cup', 120, { energyKcal: 321, proteinG: 11.8, carbohydratesG: 64.7, fatG: 1.5, fiberG: 11.2, sugarG: 0.4, sodiumMg: 17.0, calciumMg: 30.0, ironMg: 3.9, potassiumMg: 363.0, vitaminAMcg: 2.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 36.0 }, ['Gothumai', 'Gehun', 'Whole Wheat Grain'], 'Whole wheat grain used for Atta flour and Chapati.'));
rawList.push(createRawRecord('A014', 'Ragi / Finger millet, raw', 'IFCT_2017', 'A014', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Eleusine coracana', 'rice_grains', 'millets', 'cup', 100, { energyKcal: 320, proteinG: 7.3, carbohydratesG: 66.8, fatG: 1.3, fiberG: 11.5, sugarG: 0.6, sodiumMg: 11.0, calciumMg: 344.0, ironMg: 3.9, potassiumMg: 408.0, vitaminAMcg: 6.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 18.0 }, ['Kelvaragu', 'Nachni', 'Finger Millet'], 'High calcium millet traditional in South Indian porridge and Dosa.'));
rawList.push(createRawRecord('USDA_173904', 'Oats, rolled, raw', 'USDA_FDC', '173904', 'USDA FoodData Central SR Legacy', 'raw', 'Avena sativa', 'rice_grains', 'oats', 'cup', 90, { energyKcal: 389, proteinG: 16.9, carbohydratesG: 66.3, fatG: 6.9, fiberG: 10.6, sugarG: 0.99, sodiumMg: 2.0, calciumMg: 54.0, ironMg: 4.7, potassiumMg: 429.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 56.0 }, ['Rolled Oats', 'Oat Flakes'], 'Generic whole oats.'));
rawList.push(createRawRecord('A008', 'Foxtail millet / Thinai, raw', 'IFCT_2017', 'A008', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Setaria italica', 'rice_grains', 'millets', 'cup', 100, { energyKcal: 331, proteinG: 12.3, carbohydratesG: 60.9, fatG: 4.3, fiberG: 8.0, sugarG: null, sodiumMg: 4.6, calciumMg: 31.0, ironMg: 2.8, potassiumMg: 250.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 15.0 }, ['Thinai', 'Kangni', 'Foxtail Millet'], 'Traditional millet rich in protein and B vitamins.'));
rawList.push(createRawRecord('A009', 'Little millet / Samai, raw', 'IFCT_2017', 'A009', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Panicum sumatrense', 'rice_grains', 'millets', 'cup', 100, { energyKcal: 329, proteinG: 10.1, carbohydratesG: 65.5, fatG: 3.9, fiberG: 7.7, sugarG: null, sodiumMg: 8.2, calciumMg: 16.0, ironMg: 1.3, potassiumMg: 220.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 12.0 }, ['Samai', 'Kutki', 'Little Millet'], 'Small-grained millet used for Pongal and Upma.'));
rawList.push(createRawRecord('A010', 'Pearl millet / Kambu, raw', 'IFCT_2017', 'A010', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Pennisetum glaucum', 'rice_grains', 'millets', 'cup', 100, { energyKcal: 348, proteinG: 11.6, carbohydratesG: 61.8, fatG: 5.0, fiberG: 11.5, sugarG: null, sodiumMg: 10.9, calciumMg: 42.0, ironMg: 8.0, potassiumMg: 307.0, vitaminAMcg: 22.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 45.0 }, ['Kambu', 'Bajra', 'Pearl Millet'], 'Iron-rich millet consumed as Kambu Koozh in Tamil Nadu.'));
rawList.push(createRawRecord('A011', 'Sorghum / Cholam, raw', 'IFCT_2017', 'A011', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Sorghum bicolor', 'rice_grains', 'millets', 'cup', 100, { energyKcal: 334, proteinG: 9.9, carbohydratesG: 67.7, fatG: 1.7, fiberG: 10.2, sugarG: null, sodiumMg: 7.3, calciumMg: 27.0, ironMg: 3.9, potassiumMg: 274.0, vitaminAMcg: 12.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 20.0 }, ['Cholam', 'Jowar', 'Sorghum'], 'Great millet used for Roti and Dosa.'));
rawList.push(createRawRecord('A012', 'Maize / Corn, dry, raw', 'IFCT_2017', 'A012', 'ICMR-NIN IFCT 2017 Table A (Cereals)', 'raw', 'Zea mays', 'rice_grains', 'corn', 'cup', 120, { energyKcal: 334, proteinG: 8.8, carbohydratesG: 64.8, fatG: 3.8, fiberG: 12.2, sugarG: 0.6, sodiumMg: 15.9, calciumMg: 10.0, ironMg: 2.3, potassiumMg: 286.0, vitaminAMcg: 18.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 25.0 }, ['Makka Cholam', 'Makai', 'Dry Corn Grain'], 'Dry maize grain.'));

// 2. PULSES & LEGUMES (12)
rawList.push(createRawRecord('B001', 'Toor dal / Red gram, split, raw', 'IFCT_2017', 'B001', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Cajanus cajan', 'pulses_legumes', 'split_pulses', 'cup', 100, { energyKcal: 331, proteinG: 22.3, carbohydratesG: 57.6, fatG: 1.7, fiberG: 9.1, sugarG: 1.2, sodiumMg: 17.5, calciumMg: 73.0, ironMg: 2.7, potassiumMg: 1104.0, vitaminAMcg: 14.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 103.0 }, ['Thuvaram Paruppu', 'Arhar Dal', 'Pigeon Pea'], 'Primary staple pulse for Sambar and Rasam.'));
rawList.push(createRawRecord('B003', 'Urad dal / Black gram, split, raw', 'IFCT_2017', 'B003', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Vigna mungo', 'pulses_legumes', 'split_pulses', 'cup', 100, { energyKcal: 341, proteinG: 24.0, carbohydratesG: 59.6, fatG: 1.4, fiberG: 11.7, sugarG: 1.1, sodiumMg: 39.8, calciumMg: 154.0, ironMg: 3.8, potassiumMg: 983.0, vitaminAMcg: 4.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 140.0 }, ['Ulutham Paruppu', 'Urad Chilka', 'Black Gram Split'], 'Essential legume for Idli, Dosa, and Medu Vada batter.'));
rawList.push(createRawRecord('B005', 'Moong dal / Green gram, split, raw', 'IFCT_2017', 'B005', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Vigna radiata', 'pulses_legumes', 'split_pulses', 'cup', 100, { energyKcal: 334, proteinG: 24.5, carbohydratesG: 56.7, fatG: 1.2, fiberG: 8.2, sugarG: 1.5, sodiumMg: 28.0, calciumMg: 75.0, ironMg: 3.9, potassiumMg: 843.0, vitaminAMcg: 18.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 140.0 }, ['Pasi Paruppu', 'Moong Dhuli', 'Mung Bean Split'], 'Easy-to-digest pulse used for Ven Pongal and Kootu.'));
rawList.push(createRawRecord('B007', 'Chana dal / Bengal gram, split, raw', 'IFCT_2017', 'B007', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Cicer arietinum', 'pulses_legumes', 'split_pulses', 'cup', 100, { energyKcal: 372, proteinG: 20.8, carbohydratesG: 59.8, fatG: 5.6, fiberG: 10.8, sugarG: 1.8, sodiumMg: 40.0, calciumMg: 56.0, ironMg: 5.3, potassiumMg: 800.0, vitaminAMcg: 32.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 125.0 }, ['Kadalai Paruppu', 'Chana Dal', 'Split Chickpea'], 'Split chickpea used for Vadai, chutney tempering, and Sundal.'));
rawList.push(createRawRecord('B009', 'Masoor dal / Lentil, red, split, raw', 'IFCT_2017', 'B009', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Lens culinaris', 'pulses_legumes', 'split_pulses', 'cup', 100, { energyKcal: 343, proteinG: 25.1, carbohydratesG: 59.0, fatG: 0.7, fiberG: 10.7, sugarG: 1.0, sodiumMg: 10.0, calciumMg: 69.0, ironMg: 7.6, potassiumMg: 680.0, vitaminAMcg: 12.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 479.0 }, ['Red Lentil', 'Masoor Dal'], 'High folate split red lentil.'));
rawList.push(createRawRecord('B011', 'Chickpeas, whole, white / Kabuli chana, raw', 'IFCT_2017', 'B011', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Cicer arietinum', 'pulses_legumes', 'whole_legumes', 'cup', 100, { energyKcal: 360, proteinG: 19.3, carbohydratesG: 60.6, fatG: 6.0, fiberG: 17.4, sugarG: 4.8, sodiumMg: 24.0, calciumMg: 105.0, ironMg: 6.2, potassiumMg: 875.0, vitaminAMcg: 4.0, vitaminCMg: 4.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 557.0 }, ['Vella Kondakadalai', 'Kabuli Chana', 'Garbanzo Beans'], 'White chickpeas used for Chana Masala and Sundal.'));
rawList.push(createRawRecord('B012', 'Black chickpeas / Kala chana, raw', 'IFCT_2017', 'B012', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Cicer arietinum', 'pulses_legumes', 'whole_legumes', 'cup', 100, { energyKcal: 360, proteinG: 20.1, carbohydratesG: 61.2, fatG: 5.3, fiberG: 18.2, sugarG: 3.5, sodiumMg: 22.0, calciumMg: 143.0, ironMg: 4.6, potassiumMg: 810.0, vitaminAMcg: 8.0, vitaminCMg: 2.5, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 550.0 }, ['Karuppu Kondakadalai', 'Kala Chana', 'Desi Chickpea'], 'High-fiber brown desi chickpea used for Kadala curry.'));
rawList.push(createRawRecord('B014', 'Rajma / Kidney beans, red, raw', 'IFCT_2017', 'B014', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Phaseolus vulgaris', 'pulses_legumes', 'whole_legumes', 'cup', 100, { energyKcal: 333, proteinG: 22.9, carbohydratesG: 60.6, fatG: 1.3, fiberG: 24.9, sugarG: 2.2, sodiumMg: 12.0, calciumMg: 143.0, ironMg: 8.2, potassiumMg: 1406.0, vitaminAMcg: 0, vitaminCMg: 4.5, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 394.0 }, ['Rajma', 'Red Kidney Beans'], 'Protein-dense red kidney bean.'));
rawList.push(createRawRecord('B016', 'Green peas, dry, raw', 'IFCT_2017', 'B016', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Pisum sativum', 'pulses_legumes', 'whole_legumes', 'cup', 100, { energyKcal: 315, proteinG: 19.7, carbohydratesG: 56.5, fatG: 1.1, fiberG: 16.3, sugarG: 8.0, sodiumMg: 15.0, calciumMg: 75.0, ironMg: 4.4, potassiumMg: 980.0, vitaminAMcg: 15.0, vitaminCMg: 1.8, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 274.0 }, ['Pattani', 'Dry Green Peas'], 'Dried green peas for Kurma and Sundal.'));
rawList.push(createRawRecord('B018', 'Cowpeas / Karamani / Lobia, raw', 'IFCT_2017', 'B018', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Vigna unguiculata', 'pulses_legumes', 'whole_legumes', 'cup', 100, { energyKcal: 323, proteinG: 24.1, carbohydratesG: 54.5, fatG: 1.3, fiberG: 10.6, sugarG: 3.3, sodiumMg: 16.0, calciumMg: 77.0, ironMg: 8.6, potassiumMg: 1112.0, vitaminAMcg: 3.0, vitaminCMg: 1.5, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 633.0 }, ['Karamani', 'Lobia', 'Black Eyed Peas'], 'High folate cowpeas.'));
rawList.push(createRawRecord('B020', 'Soybeans, raw', 'IFCT_2017', 'B020', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Glycine max', 'pulses_legumes', 'soy', 'cup', 100, { energyKcal: 432, proteinG: 36.5, carbohydratesG: 20.9, fatG: 19.9, fiberG: 9.3, sugarG: 7.3, sodiumMg: 2.0, calciumMg: 240.0, ironMg: 10.4, potassiumMg: 1797.0, vitaminAMcg: 2.0, vitaminCMg: 6.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 375.0 }, ['Soya Bean', 'Soybean Grain'], 'Highest protein density pulse.'));
rawList.push(createRawRecord('B022', 'Horsegram / Kollu, raw', 'IFCT_2017', 'B022', 'ICMR-NIN IFCT 2017 Table B (Pulses)', 'raw', 'Macrotyloma uniflorum', 'pulses_legumes', 'whole_legumes', 'cup', 100, { energyKcal: 321, proteinG: 22.1, carbohydratesG: 57.2, fatG: 0.5, fiberG: 5.3, sugarG: null, sodiumMg: 11.5, calciumMg: 287.0, ironMg: 6.7, potassiumMg: 780.0, vitaminAMcg: 71.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 110.0 }, ['Kollu', 'Kulthi', 'Horse Gram'], 'Traditional South Indian pulse for Kollu Rasam and weight management.'));

// 3. EGGS (4)
rawList.push(createRawRecord('C001', 'Hen egg, whole, raw', 'IFCT_2017', 'C001', 'ICMR-NIN IFCT 2017 Table C (Animal Foods)', 'raw', 'Gallus gallus domesticus', 'eggs', 'whole_egg', 'piece', 50, { energyKcal: 135, proteinG: 13.3, carbohydratesG: 0.7, fatG: 8.8, fiberG: 0, sugarG: 0.7, sodiumMg: 142.0, calciumMg: 60.0, ironMg: 2.1, potassiumMg: 138.0, vitaminAMcg: 304.0, vitaminCMg: 0, vitaminDMcg: 2.2, vitaminB12Mcg: 1.1, folateMcg: 47.0 }, ['Muttai', 'Anda', 'Whole Egg'], 'Standard whole raw egg.'));
rawList.push(createRawRecord('C002', 'Hen egg, white, raw', 'IFCT_2017', 'C002', 'ICMR-NIN IFCT 2017 Table C (Animal Foods)', 'raw', 'Gallus gallus domesticus', 'eggs', 'egg_white', 'piece', 33, { energyKcal: 44, proteinG: 10.9, carbohydratesG: 0.7, fatG: 0.1, fiberG: 0, sugarG: 0.7, sodiumMg: 166.0, calciumMg: 7.0, ironMg: 0.1, potassiumMg: 163.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0.1, folateMcg: 4.0 }, ['Muttai Vella Karu', 'Anda Safed', 'Egg White'], 'Fat-free high protein egg white.'));
rawList.push(createRawRecord('C003', 'Hen egg, yolk, raw', 'IFCT_2017', 'C003', 'ICMR-NIN IFCT 2017 Table C (Animal Foods)', 'raw', 'Gallus gallus domesticus', 'eggs', 'egg_yolk', 'piece', 17, { energyKcal: 310, proteinG: 15.7, carbohydratesG: 0.6, fatG: 27.2, fiberG: 0, sugarG: 0.6, sodiumMg: 51.0, calciumMg: 140.0, ironMg: 5.5, potassiumMg: 109.0, vitaminAMcg: 1120.0, vitaminCMg: 0, vitaminDMcg: 6.8, vitaminB12Mcg: 3.5, folateMcg: 146.0 }, ['Muttai Manjal Karu', 'Egg Yolk'], 'Nutrient-rich egg yolk.'));
rawList.push(createRawRecord('C004', 'Country hen egg, whole, boiled', 'IFCT_2017', 'C004', 'ICMR-NIN IFCT 2017 Table C (Animal Foods)', 'boiled', 'Gallus gallus domesticus', 'eggs', 'whole_egg', 'piece', 50, { energyKcal: 155, proteinG: 12.6, carbohydratesG: 1.1, fatG: 10.6, fiberG: 0, sugarG: 1.1, sodiumMg: 124.0, calciumMg: 50.0, ironMg: 1.2, potassiumMg: 126.0, vitaminAMcg: 260.0, vitaminCMg: 0, vitaminDMcg: 2.0, vitaminB12Mcg: 1.0, folateMcg: 44.0 }, ['Naattu Muttai', 'Country Egg Boiled'], 'Boiled country egg.'));

// 4. CHICKEN (5)
rawList.push(createRawRecord('C010', 'Chicken, meat, raw', 'IFCT_2017', 'C010', 'ICMR-NIN IFCT 2017 Table C (Animal Foods)', 'raw', 'Gallus gallus domesticus', 'chicken', 'poultry', 'g', 100, { energyKcal: 109, proteinG: 25.9, carbohydratesG: 0, fatG: 0.6, fiberG: 0, sugarG: 0, sodiumMg: 67.0, calciumMg: 11.0, ironMg: 0.8, potassiumMg: 300.0, vitaminAMcg: 9.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: 0.3, folateMcg: 6.0 }, ['Kozhi Kkari', 'Murgh', 'Raw Chicken Meat'], 'Generic lean chicken meat.'));
rawList.push(createRawRecord('USDA_171477', 'Chicken breast, boneless, skinless, raw', 'USDA_FDC', '171477', 'USDA FoodData Central SR Legacy', 'raw', 'Gallus gallus', 'chicken', 'poultry', 'g', 150, { energyKcal: 120, proteinG: 22.5, carbohydratesG: 0, fatG: 2.6, fiberG: 0, sugarG: 0, sodiumMg: 45.0, calciumMg: 11.0, ironMg: 0.9, potassiumMg: 334.0, vitaminAMcg: 6.0, vitaminCMg: 0, vitaminDMcg: 0.1, vitaminB12Mcg: 0.34, folateMcg: 4.0 }, ['Chicken Breast', 'Boneless Chicken Breast'], 'Lean boneless skinless chicken breast.'));
rawList.push(createRawRecord('USDA_171479', 'Chicken thigh, skinless, raw', 'USDA_FDC', '171479', 'USDA FoodData Central SR Legacy', 'raw', 'Gallus gallus', 'chicken', 'poultry', 'g', 150, { energyKcal: 121, proteinG: 19.7, carbohydratesG: 0, fatG: 4.7, fiberG: 0, sugarG: 0, sodiumMg: 86.0, calciumMg: 11.0, ironMg: 1.1, potassiumMg: 247.0, vitaminAMcg: 14.0, vitaminCMg: 0, vitaminDMcg: 0.1, vitaminB12Mcg: 0.4, folateMcg: 7.0 }, ['Chicken Thigh', 'Skinless Thigh Meat'], 'Juicy skinless chicken thigh.'));
rawList.push(createRawRecord('USDA_171472', 'Chicken with skin, raw', 'USDA_FDC', '171472', 'USDA FoodData Central SR Legacy', 'raw', 'Gallus gallus', 'chicken', 'poultry', 'g', 150, { energyKcal: 215, proteinG: 18.6, carbohydratesG: 0, fatG: 15.1, fiberG: 0, sugarG: 0, sodiumMg: 72.0, calciumMg: 12.0, ironMg: 1.0, potassiumMg: 204.0, vitaminAMcg: 42.0, vitaminCMg: 0, vitaminDMcg: 0.2, vitaminB12Mcg: 0.3, folateMcg: 6.0 }, ['Chicken with Skin', 'Full Fat Chicken'], 'Chicken meat with intact skin.'));
rawList.push(createRawRecord('USDA_171480', 'Chicken mince / ground chicken, raw', 'USDA_FDC', '171480', 'USDA FoodData Central SR Legacy', 'raw', 'Gallus gallus', 'chicken', 'poultry', 'g', 100, { energyKcal: 143, proteinG: 17.4, carbohydratesG: 0, fatG: 8.1, fiberG: 0, sugarG: 0, sodiumMg: 68.0, calciumMg: 11.0, ironMg: 1.1, potassiumMg: 216.0, vitaminAMcg: 12.0, vitaminCMg: 0, vitaminDMcg: 0.1, vitaminB12Mcg: 0.35, folateMcg: 5.0 }, ['Kozhi Keema', 'Minced Chicken'], 'Finely minced chicken meat.'));

// 5. FISH & SEAFOOD (7)
rawList.push(createRawRecord('D001', 'Indian Mackerel / Ayala, raw', 'IFCT_2017', 'D001', 'ICMR-NIN IFCT 2017 Table D (Fish & Seafood)', 'raw', 'Rastrelliger kanagurta', 'fish_seafood', 'marine_fish', 'g', 150, { energyKcal: 102, proteinG: 18.9, carbohydratesG: 0.5, fatG: 2.7, fiberG: 0, sugarG: 0, sodiumMg: 82.0, calciumMg: 42.0, ironMg: 1.6, potassiumMg: 320.0, vitaminAMcg: 24.0, vitaminCMg: 0, vitaminDMcg: 8.5, vitaminB12Mcg: 8.9, folateMcg: 4.0 }, ['Ayala Meen', 'Bangda', 'Indian Mackerel'], 'Popular fatty marine fish rich in Omega-3.'));
rawList.push(createRawRecord('D005', 'Sardine / Mathi, raw', 'IFCT_2017', 'D005', 'ICMR-NIN IFCT 2017 Table D (Fish & Seafood)', 'raw', 'Sardinella longiceps', 'fish_seafood', 'marine_fish', 'g', 150, { energyKcal: 154, proteinG: 19.6, carbohydratesG: 0.8, fatG: 8.1, fiberG: 0, sugarG: 0, sodiumMg: 110.0, calciumMg: 90.0, ironMg: 2.4, potassiumMg: 380.0, vitaminAMcg: 32.0, vitaminCMg: 0, vitaminDMcg: 11.0, vitaminB12Mcg: 8.9, folateMcg: 10.0 }, ['Mathi Meen', 'Tarli', 'Oil Sardine'], 'Small oil-rich sea fish staple in Kerala and Tamil Nadu fish curry.'));
rawList.push(createRawRecord('D012', 'Rohu fish, raw', 'IFCT_2017', 'D012', 'ICMR-NIN IFCT 2017 Table D (Fish & Seafood)', 'raw', 'Labeo rohita', 'fish_seafood', 'freshwater_fish', 'g', 150, { energyKcal: 97, proteinG: 17.1, carbohydratesG: 1.1, fatG: 2.7, fiberG: 0, sugarG: 0, sodiumMg: 78.0, calciumMg: 110.0, ironMg: 1.2, potassiumMg: 288.0, vitaminAMcg: 15.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: 1.5, folateMcg: 5.0 }, ['Kannadi Meen', 'Rohu', 'Freshwater Carp'], 'Freshwater major carp fish.'));
rawList.push(createRawRecord('D015', 'Seer fish / Vanjaram / Kingfish, raw', 'IFCT_2017', 'D015', 'ICMR-NIN IFCT 2017 Table D (Fish & Seafood)', 'raw', 'Scomberomorus commerson', 'fish_seafood', 'marine_fish', 'g', 150, { energyKcal: 124, proteinG: 21.5, carbohydratesG: 0.4, fatG: 4.1, fiberG: 0, sugarG: 0, sodiumMg: 65.0, calciumMg: 38.0, ironMg: 1.1, potassiumMg: 395.0, vitaminAMcg: 18.0, vitaminCMg: 0, vitaminDMcg: 16.0, vitaminB12Mcg: 9.5, folateMcg: 2.0 }, ['Vanjaram Meen', 'Surmai', 'King Mackerel'], 'Premium firm steak sea fish for Vanjaram fry.'));
rawList.push(createRawRecord('D018', 'Pomfret, white / Vavval, raw', 'IFCT_2017', 'D018', 'ICMR-NIN IFCT 2017 Table D (Fish & Seafood)', 'raw', 'Pampus argenteus', 'fish_seafood', 'marine_fish', 'g', 150, { energyKcal: 87, proteinG: 17.2, carbohydratesG: 0.6, fatG: 1.8, fiberG: 0, sugarG: 0, sodiumMg: 95.0, calciumMg: 200.0, ironMg: 0.9, potassiumMg: 310.0, vitaminAMcg: 12.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: 2.1, folateMcg: 4.0 }, ['Vavval Meen', 'Paplet', 'Silver Pomfret'], 'Delicate white sea fish.'));
rawList.push(createRawRecord('USDA_175159', 'Tuna, yellowfin, raw', 'USDA_FDC', '175159', 'USDA FoodData Central SR Legacy', 'raw', 'Thunnus albacares', 'fish_seafood', 'marine_fish', 'g', 150, { energyKcal: 109, proteinG: 24.4, carbohydratesG: 0, fatG: 0.95, fiberG: 0, sugarG: 0, sodiumMg: 39.0, calciumMg: 4.0, ironMg: 0.77, potassiumMg: 441.0, vitaminAMcg: 18.0, vitaminCMg: 0, vitaminDMcg: 2.0, vitaminB12Mcg: 2.2, folateMcg: 2.0 }, ['Tuna Fish', 'Yellowfin Tuna'], 'Ultra-lean high protein tuna.'));
rawList.push(createRawRecord('D025', 'Prawns / Shrimp, raw', 'IFCT_2017', 'D025', 'ICMR-NIN IFCT 2017 Table D (Fish & Seafood)', 'raw', 'Penaeus monodon', 'fish_seafood', 'shellfish', 'g', 100, { energyKcal: 89, proteinG: 19.1, carbohydratesG: 0.8, fatG: 1.0, fiberG: 0, sugarG: 0, sodiumMg: 210.0, calciumMg: 323.0, ironMg: 5.3, potassiumMg: 220.0, vitaminAMcg: 14.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: 1.2, folateMcg: 3.0 }, ['Eral', 'Jhinga', 'Shrimp'], 'Lean shellfish used in Eral Thokku.'));

// 6. DAIRY (9)
rawList.push(createRawRecord('E001', 'Cow milk, whole, fresh', 'IFCT_2017', 'E001', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'fresh', 'Bos taurus', 'dairy', 'milk', 'ml', 200, { energyKcal: 67, proteinG: 3.2, carbohydratesG: 4.4, fatG: 4.1, fiberG: 0, sugarG: 4.4, sodiumMg: 73.0, calciumMg: 120.0, ironMg: 0.2, potassiumMg: 140.0, vitaminAMcg: 53.0, vitaminCMg: 1.5, vitaminDMcg: 0.1, vitaminB12Mcg: 0.4, folateMcg: 5.0 }, ['Pasu Paal', 'Cow Milk'], 'Whole fresh cow milk.'));
rawList.push(createRawRecord('E003', 'Low-fat milk / toned milk', 'IFCT_2017', 'E003', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'processed', 'Bos taurus', 'dairy', 'milk', 'ml', 200, { energyKcal: 58, proteinG: 3.3, carbohydratesG: 4.7, fatG: 3.0, fiberG: 0, sugarG: 4.7, sodiumMg: 70.0, calciumMg: 124.0, ironMg: 0.1, potassiumMg: 145.0, vitaminAMcg: 35.0, vitaminCMg: 1.0, vitaminDMcg: 0.1, vitaminB12Mcg: 0.4, folateMcg: 5.0 }, ['Toned Milk', 'Low Fat Milk'], 'Toned low fat milk.'));
rawList.push(createRawRecord('E005', 'Buffalo milk, fresh', 'IFCT_2017', 'E005', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'fresh', 'Bubalus bubalis', 'dairy', 'milk', 'ml', 200, { energyKcal: 117, proteinG: 4.3, carbohydratesG: 5.0, fatG: 6.5, fiberG: 0, sugarG: 5.0, sodiumMg: 52.0, calciumMg: 210.0, ironMg: 0.2, potassiumMg: 130.0, vitaminAMcg: 67.0, vitaminCMg: 1.0, vitaminDMcg: 0.2, vitaminB12Mcg: 0.5, folateMcg: 6.0 }, ['Erumai Paal', 'Buffalo Milk'], 'Rich whole buffalo milk.'));
rawList.push(createRawRecord('E010', 'Curd / Yogurt, whole milk', 'IFCT_2017', 'E010', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'processed', 'Bos taurus', 'dairy', 'fermented_dairy', 'cup', 150, { energyKcal: 60, proteinG: 3.1, carbohydratesG: 4.0, fatG: 3.5, fiberG: 0, sugarG: 4.0, sodiumMg: 60.0, calciumMg: 149.0, ironMg: 0.2, potassiumMg: 150.0, vitaminAMcg: 42.0, vitaminCMg: 1.0, vitaminDMcg: 0.1, vitaminB12Mcg: 0.3, folateMcg: 12.0 }, ['Thayir', 'Dahi', 'Indian Curd'], 'Traditional fermented whole milk curd.'));
rawList.push(createRawRecord('USDA_170903', 'Greek yogurt, plain, low-fat', 'USDA_FDC', '170903', 'USDA FoodData Central Foundation', 'processed', 'Bos taurus', 'dairy', 'fermented_dairy', 'cup', 150, { energyKcal: 73, proteinG: 9.9, carbohydratesG: 3.9, fatG: 1.9, fiberG: 0, sugarG: 3.6, sodiumMg: 36.0, calciumMg: 115.0, ironMg: 0.1, potassiumMg: 141.0, vitaminAMcg: 8.0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0.52, folateMcg: 7.0 }, ['Greek Yogurt', 'Strained Yogurt'], 'High protein strained plain yogurt.'));
rawList.push(createRawRecord('E015', 'Paneer / Cottage cheese', 'IFCT_2017', 'E015', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'processed', 'Bos taurus', 'dairy', 'cheese', 'g', 100, { energyKcal: 257, proteinG: 18.3, carbohydratesG: 3.0, fatG: 20.8, fiberG: 0, sugarG: 2.2, sodiumMg: 22.0, calciumMg: 480.0, ironMg: 0.4, potassiumMg: 85.0, vitaminAMcg: 210.0, vitaminCMg: 0, vitaminDMcg: 0.3, vitaminB12Mcg: 0.8, folateMcg: 18.0 }, ['Paneer', 'Indian Cottage Cheese'], 'Fresh acid-coagulated milk curd cheese.'));
rawList.push(createRawRecord('E018', 'Buttermilk / Moru', 'IFCT_2017', 'E018', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'processed', 'Bos taurus', 'dairy', 'fermented_dairy', 'glass', 200, { energyKcal: 19, proteinG: 0.8, carbohydratesG: 1.2, fatG: 1.1, fiberG: 0, sugarG: 1.2, sodiumMg: 20.0, calciumMg: 30.0, ironMg: 0.05, potassiumMg: 45.0, vitaminAMcg: 10.0, vitaminCMg: 0.2, vitaminDMcg: 0, vitaminB12Mcg: 0.1, folateMcg: 3.0 }, ['Moru', 'Chaas', 'Spiced Buttermilk'], 'Diluted churned curd beverage.'));
rawList.push(createRawRecord('E022', 'Ghee / Clarified butter', 'IFCT_2017', 'E022', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'processed', 'Bos taurus', 'dairy', 'fats', 'tbsp', 14, { energyKcal: 897, proteinG: 0, carbohydratesG: 0, fatG: 99.5, fiberG: 0, sugarG: 0, sodiumMg: 0, calciumMg: 3.0, ironMg: 0.02, potassiumMg: 1.0, vitaminAMcg: 800.0, vitaminCMg: 0, vitaminDMcg: 1.2, vitaminB12Mcg: 0, folateMcg: 0 }, ['Ney', 'Desi Ghee', 'Clarified Butter'], 'Pure clarified butter fat.'));
rawList.push(createRawRecord('E025', 'Butter, unsalted', 'IFCT_2017', 'E025', 'ICMR-NIN IFCT 2017 Table E (Milk & Milk Products)', 'processed', 'Bos taurus', 'dairy', 'fats', 'tbsp', 14, { energyKcal: 717, proteinG: 0.8, carbohydratesG: 0.1, fatG: 81.1, fiberG: 0, sugarG: 0.1, sodiumMg: 11.0, calciumMg: 24.0, ironMg: 0.02, potassiumMg: 24.0, vitaminAMcg: 684.0, vitaminCMg: 0, vitaminDMcg: 1.5, vitaminB12Mcg: 0.2, folateMcg: 3.0 }, ['Vennai', 'Makhan', 'Unsalted Butter'], 'Commercial dairy butter.'));

// 7. VEGETABLES (25)
rawList.push(createRawRecord('F001', 'Onion, red, raw', 'IFCT_2017', 'F001', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Allium cepa', 'vegetables', 'alliums', 'piece', 80, { energyKcal: 48, proteinG: 1.2, carbohydratesG: 9.9, fatG: 0.1, fiberG: 2.1, sugarG: 4.8, sodiumMg: 4.0, calciumMg: 47.0, ironMg: 0.6, potassiumMg: 157.0, vitaminAMcg: 0, vitaminCMg: 8.5, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 19.0 }, ['Vengayam', 'Pyaz', 'Red Onion'], 'Red onion essential for South Indian cooking base.'));
rawList.push(createRawRecord('F005', 'Tomato, ripe, raw', 'IFCT_2017', 'F005', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Solanum lycopersicum', 'vegetables', 'solanaceous', 'piece', 90, { energyKcal: 20, proteinG: 0.9, carbohydratesG: 3.6, fatG: 0.2, fiberG: 1.7, sugarG: 2.6, sodiumMg: 13.0, calciumMg: 12.0, ironMg: 0.4, potassiumMg: 194.0, vitaminAMcg: 320.0, vitaminCMg: 27.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 15.0 }, ['Thakkali', 'Tamatar', 'Ripe Tomato'], 'Ripe red tomato for Sambar, Rasam, and Chutney.'));
rawList.push(createRawRecord('F010', 'Potato, raw', 'IFCT_2017', 'F010', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Solanum tuberosum', 'vegetables', 'tubers', 'piece', 120, { energyKcal: 77, proteinG: 1.6, carbohydratesG: 17.2, fatG: 0.1, fiberG: 1.3, sugarG: 0.6, sodiumMg: 11.0, calciumMg: 10.0, ironMg: 0.5, potassiumMg: 247.0, vitaminAMcg: 4.0, vitaminCMg: 17.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 18.0 }, ['Urulaikizhangu', 'Aloo', 'Potato'], 'Starchy tuber used in Masala Dosa filling.'));
rawList.push(createRawRecord('F015', 'Carrot, orange, raw', 'IFCT_2017', 'F015', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Daucus carota', 'vegetables', 'roots', 'piece', 70, { energyKcal: 48, proteinG: 0.9, carbohydratesG: 10.6, fatG: 0.2, fiberG: 4.4, sugarG: 5.2, sodiumMg: 35.0, calciumMg: 34.0, ironMg: 0.9, potassiumMg: 240.0, vitaminAMcg: 835.0, vitaminCMg: 3.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 19.0 }, ['Carrot', 'Gajar', 'Orange Carrot'], 'Beta-carotene rich orange root vegetable.'));
rawList.push(createRawRecord('F020', 'French beans, raw', 'IFCT_2017', 'F020', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Phaseolus vulgaris', 'vegetables', 'pods', 'cup', 100, { energyKcal: 26, proteinG: 1.7, carbohydratesG: 4.5, fatG: 0.1, fiberG: 1.8, sugarG: 1.4, sodiumMg: 6.0, calciumMg: 50.0, ironMg: 0.6, potassiumMg: 180.0, vitaminAMcg: 35.0, vitaminCMg: 11.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 37.0 }, ['Beans', 'French Beans'], 'Green pods used for Poriyal.'));
rawList.push(createRawRecord('F025', 'Cabbage, raw', 'IFCT_2017', 'F025', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Brassica oleracea var. capitata', 'vegetables', 'cruciferous', 'cup', 90, { energyKcal: 21, proteinG: 1.3, carbohydratesG: 4.4, fatG: 0.1, fiberG: 2.8, sugarG: 2.3, sodiumMg: 12.0, calciumMg: 39.0, ironMg: 0.8, potassiumMg: 170.0, vitaminAMcg: 12.0, vitaminCMg: 36.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 43.0 }, ['Muttaikose', 'Patta Gobhi', 'Green Cabbage'], 'Leafy cruciferous head vegetable.'));
rawList.push(createRawRecord('F030', 'Cauliflower, raw', 'IFCT_2017', 'F030', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Brassica oleracea var. botrytis', 'vegetables', 'cruciferous', 'cup', 100, { energyKcal: 25, proteinG: 2.0, carbohydratesG: 4.9, fatG: 0.3, fiberG: 2.0, sugarG: 1.9, sodiumMg: 30.0, calciumMg: 33.0, ironMg: 1.2, potassiumMg: 300.0, vitaminAMcg: 15.0, vitaminCMg: 48.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 57.0 }, ['Gobi', 'Cauliflower Florets'], 'Cruciferous florets.'));
rawList.push(createRawRecord('F035', 'Brinjal / Eggplant / Kathirikai, raw', 'IFCT_2017', 'F035', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Solanum melongena', 'vegetables', 'solanaceous', 'piece', 100, { energyKcal: 24, proteinG: 1.4, carbohydratesG: 4.0, fatG: 0.2, fiberG: 2.5, sugarG: 2.3, sodiumMg: 3.0, calciumMg: 18.0, ironMg: 0.4, potassiumMg: 200.0, vitaminAMcg: 27.0, vitaminCMg: 12.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 22.0 }, ['Kathirikai', 'Baingan', 'Eggplant'], 'Purple eggplant for Sambar, Vatha Kuzhambu, and Ennai Kathirikai.'));
rawList.push(createRawRecord('F040', 'Drumstick / Murungakkai, raw', 'IFCT_2017', 'F040', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Moringa oleifera', 'vegetables', 'pods', 'piece', 50, { energyKcal: 37, proteinG: 2.1, carbohydratesG: 8.5, fatG: 0.2, fiberG: 3.2, sugarG: null, sodiumMg: 42.0, calciumMg: 30.0, ironMg: 0.5, potassiumMg: 259.0, vitaminAMcg: 74.0, vitaminCMg: 120.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 40.0 }, ['Murungakkai', 'Drumstick Pod'], 'Moringa pod staple in Sambar.'));
rawList.push(createRawRecord('F045', 'Bottle gourd / Sorakkay, raw', 'IFCT_2017', 'F045', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Lagenaria siceraria', 'vegetables', 'gourds', 'cup', 100, { energyKcal: 14, proteinG: 0.6, carbohydratesG: 2.5, fatG: 0.1, fiberG: 0.6, sugarG: 1.2, sodiumMg: 2.0, calciumMg: 20.0, ironMg: 0.5, potassiumMg: 150.0, vitaminAMcg: 0, vitaminCMg: 10.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 6.0 }, ['Sorakkay', 'Lauki', 'Bottle Gourd'], 'Low calorie hydration gourd used in Kootu.'));
rawList.push(createRawRecord('F050', 'Ridge gourd / Peerkangai, raw', 'IFCT_2017', 'F050', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Luffa acutangula', 'vegetables', 'gourds', 'cup', 100, { energyKcal: 17, proteinG: 0.5, carbohydratesG: 3.4, fatG: 0.1, fiberG: 2.0, sugarG: 1.1, sodiumMg: 3.0, calciumMg: 18.0, ironMg: 0.4, potassiumMg: 140.0, vitaminAMcg: 33.0, vitaminCMg: 5.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 7.0 }, ['Peerkangai', 'Turai', 'Ridge Gourd'], 'Ribbed gourd vegetable.'));
rawList.push(createRawRecord('F055', 'Bitter gourd / Pavakkai, raw', 'IFCT_2017', 'F055', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Momordica charantia', 'vegetables', 'gourds', 'cup', 90, { energyKcal: 17, proteinG: 1.0, carbohydratesG: 3.7, fatG: 0.1, fiberG: 2.8, sugarG: 1.0, sodiumMg: 5.0, calciumMg: 19.0, ironMg: 0.4, potassiumMg: 319.0, vitaminAMcg: 24.0, vitaminCMg: 84.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 72.0 }, ['Pavakkai', 'Karela', 'Bitter Melon'], 'Bitter medicinal gourd used in Pitlai and Fry.'));
rawList.push(createRawRecord('F060', 'Snake gourd / Pudalangai, raw', 'IFCT_2017', 'F060', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Trichosanthes cucumerina', 'vegetables', 'gourds', 'cup', 100, { energyKcal: 18, proteinG: 0.6, carbohydratesG: 3.3, fatG: 0.3, fiberG: 1.5, sugarG: 1.3, sodiumMg: 2.5, calciumMg: 26.0, ironMg: 0.5, potassiumMg: 130.0, vitaminAMcg: 15.0, vitaminCMg: 5.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 10.0 }, ['Pudalangai', 'Chichinda', 'Snake Gourd'], 'Long striped gourd for Kootu and Poriyal.'));
rawList.push(createRawRecord('F065', 'Ladies finger / Okra / Vendakkai, raw', 'IFCT_2017', 'F065', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Abelmoschus esculentus', 'vegetables', 'pods', 'cup', 100, { energyKcal: 33, proteinG: 1.9, carbohydratesG: 7.5, fatG: 0.2, fiberG: 3.2, sugarG: 1.5, sodiumMg: 7.0, calciumMg: 82.0, ironMg: 0.6, potassiumMg: 299.0, vitaminAMcg: 36.0, vitaminCMg: 23.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 60.0 }, ['Vendakkai', 'Bhindi', 'Okra'], 'Slimy green pod for Vendakkai Mandi and Sambar.'));
rawList.push(createRawRecord('F070', 'Pumpkin / Pooshanikkay, yellow, raw', 'IFCT_2017', 'F070', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Cucurbita moschata', 'vegetables', 'gourds', 'cup', 100, { energyKcal: 26, proteinG: 1.0, carbohydratesG: 6.5, fatG: 0.1, fiberG: 1.1, sugarG: 2.8, sodiumMg: 1.0, calciumMg: 21.0, ironMg: 0.8, potassiumMg: 340.0, vitaminAMcg: 426.0, vitaminCMg: 9.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 16.0 }, ['Manjal Pooshani', 'Kaddu', 'Yellow Pumpkin'], 'Sweet orange flesh gourd used in More Kuzhambu.'));
rawList.push(createRawRecord('F075', 'Beetroot, raw', 'IFCT_2017', 'F075', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Beta vulgaris', 'vegetables', 'roots', 'piece', 100, { energyKcal: 43, proteinG: 1.6, carbohydratesG: 9.6, fatG: 0.2, fiberG: 2.8, sugarG: 6.8, sodiumMg: 78.0, calciumMg: 16.0, ironMg: 0.8, potassiumMg: 325.0, vitaminAMcg: 2.0, vitaminCMg: 4.9, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 109.0 }, ['Beetroot', 'Chukandar'], 'Deep red root for Poriyal and Halwa.'));
rawList.push(createRawRecord('F080', 'Green peas, fresh, raw', 'IFCT_2017', 'F080', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Pisum sativum', 'vegetables', 'pods', 'cup', 100, { energyKcal: 81, proteinG: 5.4, carbohydratesG: 14.5, fatG: 0.4, fiberG: 5.1, sugarG: 5.7, sodiumMg: 5.0, calciumMg: 25.0, ironMg: 1.5, potassiumMg: 244.0, vitaminAMcg: 38.0, vitaminCMg: 40.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 65.0 }, ['Pasi Pattani', 'Matar', 'Fresh Green Peas'], 'Fresh sweet green peas.'));
rawList.push(createRawRecord('F085', 'Capsicum / Green bell pepper, raw', 'IFCT_2017', 'F085', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Capsicum annuum', 'vegetables', 'solanaceous', 'piece', 100, { energyKcal: 20, proteinG: 0.9, carbohydratesG: 4.6, fatG: 0.2, fiberG: 1.7, sugarG: 2.4, sodiumMg: 3.0, calciumMg: 10.0, ironMg: 0.4, potassiumMg: 175.0, vitaminAMcg: 18.0, vitaminCMg: 80.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 10.0 }, ['Kudai Milagai', 'Shimla Mirch', 'Green Bell Pepper'], 'Crunchy green pepper.'));
rawList.push(createRawRecord('F090', 'Cucumber / Vellarikkay, raw', 'IFCT_2017', 'F090', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Cucumis sativus', 'vegetables', 'gourds', 'piece', 120, { energyKcal: 15, proteinG: 0.7, carbohydratesG: 3.6, fatG: 0.1, fiberG: 0.5, sugarG: 1.7, sodiumMg: 2.0, calciumMg: 16.0, ironMg: 0.3, potassiumMg: 147.0, vitaminAMcg: 5.0, vitaminCMg: 2.8, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 7.0 }, ['Vellarikkay', 'Kheera', 'Cucumber'], 'Hydrating cucumber.'));
rawList.push(createRawRecord('F095', 'Radish, white / Mullangi, raw', 'IFCT_2017', 'F095', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Raphanus sativus', 'vegetables', 'roots', 'piece', 90, { energyKcal: 16, proteinG: 0.7, carbohydratesG: 3.4, fatG: 0.1, fiberG: 1.6, sugarG: 1.9, sodiumMg: 39.0, calciumMg: 25.0, ironMg: 0.3, potassiumMg: 233.0, vitaminAMcg: 0, vitaminCMg: 15.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 25.0 }, ['Mullangi', 'Mooli', 'White Radish'], 'Pungent white root for Mullangi Sambar.'));
rawList.push(createRawRecord('F100', 'Button Mushroom, raw', 'IFCT_2017', 'F100', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Agaricus bisporus', 'vegetables', 'fungi', 'cup', 90, { energyKcal: 22, proteinG: 3.1, carbohydratesG: 3.3, fatG: 0.3, fiberG: 1.0, sugarG: 2.0, sodiumMg: 5.0, calciumMg: 3.0, ironMg: 0.5, potassiumMg: 318.0, vitaminAMcg: 0, vitaminCMg: 2.1, vitaminDMcg: 0.2, vitaminB12Mcg: 0.04, folateMcg: 17.0 }, ['Kalan', 'Mushroom'], 'White button mushroom used in Kaalan Curry.'));
rawList.push(createRawRecord('F105', 'Ash gourd / Neer pooshani, raw', 'IFCT_2017', 'F105', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Benincasa hispida', 'vegetables', 'gourds', 'cup', 100, { energyKcal: 13, proteinG: 0.4, carbohydratesG: 3.0, fatG: 0.2, fiberG: 2.9, sugarG: 1.1, sodiumMg: 6.0, calciumMg: 30.0, ironMg: 0.8, potassiumMg: 111.0, vitaminAMcg: 0, vitaminCMg: 13.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 5.0 }, ['Neer Pooshani', 'Petha', 'Winter Melon'], 'White cooling gourd for More Kuzhambu.'));
rawList.push(createRawRecord('F110', 'Plantain, raw / Vazhaikkai', 'IFCT_2017', 'F110', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Musa paradisiaca', 'vegetables', 'green_fruit_veg', 'piece', 120, { energyKcal: 89, proteinG: 1.3, carbohydratesG: 22.8, fatG: 0.3, fiberG: 2.3, sugarG: null, sodiumMg: 4.0, calciumMg: 10.0, ironMg: 0.6, potassiumMg: 358.0, vitaminAMcg: 56.0, vitaminCMg: 18.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 22.0 }, ['Vazhaikkai', 'Raw Banana', 'Green Plantain'], 'Starchy green banana for Vazhaikkai Varuval.'));
rawList.push(createRawRecord('F115', 'Yam / Senai kizhangu, raw', 'IFCT_2017', 'F115', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Dioscorea alata', 'vegetables', 'tubers', 'cup', 100, { energyKcal: 118, proteinG: 1.5, carbohydratesG: 27.9, fatG: 0.2, fiberG: 4.1, sugarG: 0.5, sodiumMg: 9.0, calciumMg: 17.0, ironMg: 0.5, potassiumMg: 816.0, vitaminAMcg: 8.0, vitaminCMg: 17.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 23.0 }, ['Senai Kizhangu', 'Suran', 'Elephant Foot Yam'], 'Large starchy tuber for Senai Roast.'));
rawList.push(createRawRecord('F120', 'Tapioca / Maravalli kizhangu, raw', 'IFCT_2017', 'F120', 'ICMR-NIN IFCT 2017 Table F (Vegetables)', 'raw', 'Manihot esculenta', 'vegetables', 'tubers', 'cup', 100, { energyKcal: 160, proteinG: 1.4, carbohydratesG: 38.1, fatG: 0.3, fiberG: 1.8, sugarG: 1.7, sodiumMg: 14.0, calciumMg: 16.0, ironMg: 0.3, potassiumMg: 271.0, vitaminAMcg: 1.0, vitaminCMg: 20.6, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 27.0 }, ['Maravalli Kizhangu', 'Cassava', 'Tapioca'], 'Starchy root tuber staple in Kerala (Kappa).'));

// 8. FRUITS (13)
rawList.push(createRawRecord('G001', 'Banana, Cavendish / Poovan, ripe', 'IFCT_2017', 'G001', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Musa acuminata', 'fruits', 'tropical_fruits', 'piece', 100, { energyKcal: 89, proteinG: 1.1, carbohydratesG: 22.8, fatG: 0.3, fiberG: 2.6, sugarG: 12.2, sodiumMg: 1.0, calciumMg: 5.0, ironMg: 0.3, potassiumMg: 358.0, vitaminAMcg: 64.0, vitaminCMg: 8.7, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 20.0 }, ['Vazhaipazham', 'Kela', 'Poovan Banana'], 'Ripe yellow sweet banana.'));
rawList.push(createRawRecord('G005', 'Apple, red, raw', 'IFCT_2017', 'G005', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Malus domestica', 'fruits', 'temperate_fruits', 'piece', 150, { energyKcal: 52, proteinG: 0.3, carbohydratesG: 13.8, fatG: 0.2, fiberG: 2.4, sugarG: 10.4, sodiumMg: 1.0, calciumMg: 6.0, ironMg: 0.1, potassiumMg: 107.0, vitaminAMcg: 3.0, vitaminCMg: 4.6, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 3.0 }, ['Apple', 'Seb'], 'Crisp red apple.'));
rawList.push(createRawRecord('G010', 'Orange, sweet / Satukudi, raw', 'IFCT_2017', 'G010', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Citrus sinensis', 'fruits', 'citrus_fruits', 'piece', 130, { energyKcal: 47, proteinG: 0.9, carbohydratesG: 11.8, fatG: 0.1, fiberG: 2.4, sugarG: 9.4, sodiumMg: 0, calciumMg: 40.0, ironMg: 0.1, potassiumMg: 181.0, vitaminAMcg: 11.0, vitaminCMg: 53.2, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 30.0 }, ['Kichili', 'Satukudi', 'Sweet Orange'], 'Juicy citrus fruit.'));
rawList.push(createRawRecord('G015', 'Guava, white flesh, raw', 'IFCT_2017', 'G015', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Psidium guajava', 'fruits', 'tropical_fruits', 'piece', 100, { energyKcal: 68, proteinG: 2.6, carbohydratesG: 14.3, fatG: 1.0, fiberG: 5.4, sugarG: 8.9, sodiumMg: 2.0, calciumMg: 18.0, ironMg: 0.3, potassiumMg: 417.0, vitaminAMcg: 31.0, vitaminCMg: 228.3, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 49.0 }, ['Koyyapazham', 'Amrood', 'White Guava'], 'Vitamin-C dense white guava.'));
rawList.push(createRawRecord('G020', 'Papaya, ripe, raw', 'IFCT_2017', 'G020', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Carica papaya', 'fruits', 'tropical_fruits', 'cup', 140, { energyKcal: 43, proteinG: 0.5, carbohydratesG: 10.8, fatG: 0.3, fiberG: 1.7, sugarG: 7.8, sodiumMg: 8.0, calciumMg: 20.0, ironMg: 0.25, potassiumMg: 182.0, vitaminAMcg: 950.0, vitaminCMg: 60.9, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 37.0 }, ['Pappali', 'Papita', 'Ripe Papaya'], 'Beta-carotene rich ripe papaya.'));
rawList.push(createRawRecord('G025', 'Watermelon, raw', 'IFCT_2017', 'G025', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Citrullus lanatus', 'fruits', 'melons', 'cup', 150, { energyKcal: 30, proteinG: 0.6, carbohydratesG: 7.6, fatG: 0.2, fiberG: 0.4, sugarG: 6.2, sodiumMg: 1.0, calciumMg: 7.0, ironMg: 0.2, potassiumMg: 112.0, vitaminAMcg: 28.0, vitaminCMg: 8.1, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 3.0 }, ['Thannir Mathan', 'Tarbooz', 'Watermelon'], 'Refreshing hydrating melon.'));
rawList.push(createRawRecord('G030', 'Pineapple, raw', 'IFCT_2017', 'G030', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Ananas comosus', 'fruits', 'tropical_fruits', 'cup', 150, { energyKcal: 50, proteinG: 0.5, carbohydratesG: 13.1, fatG: 0.1, fiberG: 1.4, sugarG: 9.9, sodiumMg: 1.0, calciumMg: 13.0, ironMg: 0.3, potassiumMg: 109.0, vitaminAMcg: 3.0, vitaminCMg: 47.8, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 18.0 }, ['Ananas', 'Pineapple'], 'Bromelain rich tropical fruit.'));
rawList.push(createRawRecord('G035', 'Mango, ripe / Alphonso/Neelum, raw', 'IFCT_2017', 'G035', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Mangifera indica', 'fruits', 'tropical_fruits', 'cup', 150, { energyKcal: 60, proteinG: 0.8, carbohydratesG: 15.0, fatG: 0.4, fiberG: 1.6, sugarG: 13.7, sodiumMg: 1.0, calciumMg: 11.0, ironMg: 0.16, potassiumMg: 168.0, vitaminAMcg: 1080.0, vitaminCMg: 36.4, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 43.0 }, ['Mambazham', 'Aam', 'Ripe Mango'], 'King of tropical fruits.'));
rawList.push(createRawRecord('G040', 'Pomegranate, raw', 'IFCT_2017', 'G040', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Punica granatum', 'fruits', 'exotic_fruits', 'cup', 150, { energyKcal: 83, proteinG: 1.7, carbohydratesG: 18.7, fatG: 1.2, fiberG: 4.0, sugarG: 13.7, sodiumMg: 3.0, calciumMg: 10.0, ironMg: 0.3, potassiumMg: 236.0, vitaminAMcg: 0, vitaminCMg: 10.2, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 38.0 }, ['Maadulam', 'Anar', 'Pomegranate Arils'], 'Antioxidant red aril fruit.'));
rawList.push(createRawRecord('G045', 'Grapes, green, raw', 'IFCT_2017', 'G045', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Vitis vinifera', 'fruits', 'berries', 'cup', 150, { energyKcal: 69, proteinG: 0.7, carbohydratesG: 18.1, fatG: 0.2, fiberG: 0.9, sugarG: 15.5, sodiumMg: 2.0, calciumMg: 10.0, ironMg: 0.36, potassiumMg: 191.0, vitaminAMcg: 3.0, vitaminCMg: 3.2, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 2.0 }, ['Drakshai', 'Angoor', 'Green Grapes'], 'Sweet seedless green grapes.'));
rawList.push(createRawRecord('G050', 'Muskmelon / Kirni fruit, raw', 'IFCT_2017', 'G050', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Cucumis melo', 'fruits', 'melons', 'cup', 150, { energyKcal: 34, proteinG: 0.8, carbohydratesG: 8.2, fatG: 0.2, fiberG: 0.9, sugarG: 7.9, sodiumMg: 16.0, calciumMg: 9.0, ironMg: 0.2, potassiumMg: 267.0, vitaminAMcg: 169.0, vitaminCMg: 36.7, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 21.0 }, ['Kirni Pazham', 'Kharbooza', 'Cantaloupe'], 'Sweet orange cantaloupe melon.'));
rawList.push(createRawRecord('G055', 'Sapota / Chikoo, raw', 'IFCT_2017', 'G055', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Manilkara zapota', 'fruits', 'tropical_fruits', 'piece', 90, { energyKcal: 83, proteinG: 0.4, carbohydratesG: 20.0, fatG: 1.1, fiberG: 5.3, sugarG: 14.2, sodiumMg: 12.0, calciumMg: 21.0, ironMg: 0.8, potassiumMg: 193.0, vitaminAMcg: 3.0, vitaminCMg: 14.7, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 14.0 }, ['Chikoo', 'Sapota', 'Sapodilla'], 'High fiber brown tropical fruit.'));
rawList.push(createRawRecord('G060', 'Jackfruit, ripe, raw', 'IFCT_2017', 'G060', 'ICMR-NIN IFCT 2017 Table G (Fruits)', 'fresh', 'Artocarpus heterophyllus', 'fruits', 'tropical_fruits', 'cup', 150, { energyKcal: 95, proteinG: 1.7, carbohydratesG: 23.3, fatG: 0.6, fiberG: 1.5, sugarG: 19.1, sodiumMg: 2.0, calciumMg: 24.0, ironMg: 0.2, potassiumMg: 448.0, vitaminAMcg: 5.0, vitaminCMg: 13.7, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 24.0 }, ['Palaapazham', 'Kathal', 'Ripe Jackfruit'], 'Sweet golden jackfruit bulbs.'));

// 9. NUTS & SEEDS (10)
rawList.push(createRawRecord('H001', 'Peanut / Groundnut, dry, raw', 'IFCT_2017', 'H001', 'ICMR-NIN IFCT 2017 Table H (Nuts & Oilseeds)', 'raw', 'Arachis hypogaea', 'nuts_seeds', 'nuts', 'g', 30, { energyKcal: 567, proteinG: 25.8, carbohydratesG: 16.1, fatG: 49.2, fiberG: 8.5, sugarG: 4.7, sodiumMg: 18.0, calciumMg: 92.0, ironMg: 4.6, potassiumMg: 705.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 240.0 }, ['Kadalai', 'Moongphali', 'Peanuts'], 'Peanuts used in Sundal, chutney, and oil.'));
rawList.push(createRawRecord('H005', 'Almond, raw', 'IFCT_2017', 'H005', 'ICMR-NIN IFCT 2017 Table H (Nuts & Oilseeds)', 'raw', 'Prunus dulcis', 'nuts_seeds', 'tree_nuts', 'g', 30, { energyKcal: 579, proteinG: 21.2, carbohydratesG: 21.7, fatG: 49.9, fiberG: 12.5, sugarG: 4.4, sodiumMg: 1.0, calciumMg: 269.0, ironMg: 3.7, potassiumMg: 733.0, vitaminAMcg: 1.0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 44.0 }, ['Badam', 'Almond'], 'Nutrient dense tree nut.'));
rawList.push(createRawRecord('H010', 'Cashew nut, raw', 'IFCT_2017', 'H010', 'ICMR-NIN IFCT 2017 Table H (Nuts & Oilseeds)', 'raw', 'Anacardium occidentale', 'nuts_seeds', 'tree_nuts', 'g', 30, { energyKcal: 553, proteinG: 18.2, carbohydratesG: 30.2, fatG: 43.8, fiberG: 3.3, sugarG: 5.9, sodiumMg: 12.0, calciumMg: 37.0, ironMg: 6.7, potassiumMg: 660.0, vitaminAMcg: 0, vitaminCMg: 0.5, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 25.0 }, ['Munthiri', 'Kaju', 'Cashew'], 'Rich nut for Payasam and Biryani garnishing.'));
rawList.push(createRawRecord('H015', 'Walnut, raw', 'IFCT_2017', 'H015', 'ICMR-NIN IFCT 2017 Table H (Nuts & Oilseeds)', 'raw', 'Juglans regia', 'nuts_seeds', 'tree_nuts', 'g', 30, { energyKcal: 654, proteinG: 15.2, carbohydratesG: 13.7, fatG: 65.2, fiberG: 6.7, sugarG: 2.6, sodiumMg: 2.0, calciumMg: 98.0, ironMg: 2.9, potassiumMg: 441.0, vitaminAMcg: 1.0, vitaminCMg: 1.3, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 98.0 }, ['Akhrot', 'Walnut'], 'Omega-3 ALA rich tree nut.'));
rawList.push(createRawRecord('H020', 'Pistachio nut, raw', 'IFCT_2017', 'H020', 'ICMR-NIN IFCT 2017 Table H (Nuts & Oilseeds)', 'raw', 'Pistacia vera', 'nuts_seeds', 'tree_nuts', 'g', 30, { energyKcal: 562, proteinG: 20.2, carbohydratesG: 27.2, fatG: 45.3, fiberG: 10.6, sugarG: 7.7, sodiumMg: 1.0, calciumMg: 105.0, ironMg: 3.9, potassiumMg: 1025.0, vitaminAMcg: 26.0, vitaminCMg: 5.6, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 51.0 }, ['Pista', 'Pistachio'], 'Green kernel tree nut.'));
rawList.push(createRawRecord('USDA_170554', 'Chia seeds, raw', 'USDA_FDC', '170554', 'USDA FoodData Central Foundation', 'raw', 'Salvia hispanica', 'nuts_seeds', 'seeds', 'tbsp', 12, { energyKcal: 486, proteinG: 16.5, carbohydratesG: 42.1, fatG: 30.7, fiberG: 34.4, sugarG: 0, sodiumMg: 16.0, calciumMg: 631.0, ironMg: 7.7, potassiumMg: 407.0, vitaminAMcg: 54.0, vitaminCMg: 1.6, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 49.0 }, ['Chia Seeds'], 'High fiber mucilaginous seed.'));
rawList.push(createRawRecord('H025', 'Flax seeds / Ali vidai, raw', 'IFCT_2017', 'H025', 'ICMR-NIN IFCT 2017 Table H (Nuts & Oilseeds)', 'raw', 'Linum usitatissimum', 'nuts_seeds', 'seeds', 'tbsp', 10, { energyKcal: 534, proteinG: 18.3, carbohydratesG: 28.9, fatG: 42.2, fiberG: 27.3, sugarG: 1.6, sodiumMg: 30.0, calciumMg: 255.0, ironMg: 5.7, potassiumMg: 813.0, vitaminAMcg: 0, vitaminCMg: 0.6, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 87.0 }, ['Ali Vidai', 'Alsi', 'Flax Seeds'], 'Rich in Omega-3 lignans.'));
rawList.push(createRawRecord('H030', 'Sesame seeds, white / Ellu, raw', 'IFCT_2017', 'H030', 'ICMR-NIN IFCT 2017 Table H (Nuts & Oilseeds)', 'raw', 'Sesamum indicum', 'nuts_seeds', 'seeds', 'tbsp', 10, { energyKcal: 573, proteinG: 17.7, carbohydratesG: 23.4, fatG: 49.7, fiberG: 11.8, sugarG: 0.3, sodiumMg: 11.0, calciumMg: 975.0, ironMg: 14.6, potassiumMg: 468.0, vitaminAMcg: 1.0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 97.0 }, ['Ellu', 'Til', 'White Sesame'], 'Ultra high calcium sesame seed.'));
rawList.push(createRawRecord('USDA_170562', 'Sunflower seeds, raw', 'USDA_FDC', '170562', 'USDA FoodData Central Foundation', 'raw', 'Helianthus annuus', 'nuts_seeds', 'seeds', 'tbsp', 10, { energyKcal: 584, proteinG: 20.8, carbohydratesG: 20.0, fatG: 51.5, fiberG: 8.6, sugarG: 2.6, sodiumMg: 9.0, calciumMg: 78.0, ironMg: 5.2, potassiumMg: 645.0, vitaminAMcg: 3.0, vitaminCMg: 1.4, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 227.0 }, ['Sunflower Seeds'], 'Vitamin E rich seed.'));
rawList.push(createRawRecord('USDA_170556', 'Pumpkin seeds, raw', 'USDA_FDC', '170556', 'USDA FoodData Central Foundation', 'raw', 'Cucurbita pepo', 'nuts_seeds', 'seeds', 'tbsp', 10, { energyKcal: 559, proteinG: 30.2, carbohydratesG: 10.7, fatG: 49.1, fiberG: 6.0, sugarG: 1.4, sodiumMg: 7.0, calciumMg: 46.0, ironMg: 8.8, potassiumMg: 809.0, vitaminAMcg: 1.0, vitaminCMg: 1.9, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 58.0 }, ['Pumpkin Seeds', 'Pepitas'], 'Zinc and magnesium rich seed.'));

// 10. OILS & FATS (7)
rawList.push(createRawRecord('I001', 'Groundnut oil / Peanut oil', 'IFCT_2017', 'I001', 'ICMR-NIN IFCT 2017 Table I (Fats & Oils)', 'processed', 'Arachis hypogaea', 'oils_fats', 'vegetable_oil', 'tbsp', 14, { energyKcal: 884, proteinG: 0, carbohydratesG: 0, fatG: 100.0, fiberG: 0, sugarG: 0, sodiumMg: 0, calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Kadalai Ennai', 'Moongphali Tel', 'Peanut Oil'], 'Cold pressed groundnut oil staple in Tamil Nadu.'));
rawList.push(createRawRecord('I005', 'Sesame oil / Gingelly oil / Nalla ennai', 'IFCT_2017', 'I005', 'ICMR-NIN IFCT 2017 Table I (Fats & Oils)', 'processed', 'Sesamum indicum', 'oils_fats', 'vegetable_oil', 'tbsp', 14, { energyKcal: 884, proteinG: 0, carbohydratesG: 0, fatG: 100.0, fiberG: 0, sugarG: 0, sodiumMg: 0, calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Nalla Ennai', 'Til Tel', 'Gingelly Oil'], 'Traditional sesame cooking oil for South Indian curry.'));
rawList.push(createRawRecord('I010', 'Coconut oil', 'IFCT_2017', 'I010', 'ICMR-NIN IFCT 2017 Table I (Fats & Oils)', 'processed', 'Cocos nucifera', 'oils_fats', 'tropical_oil', 'tbsp', 14, { energyKcal: 862, proteinG: 0, carbohydratesG: 0, fatG: 100.0, fiberG: 0, sugarG: 0, sodiumMg: 0, calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Thengai Ennai', 'Nariyal Tel', 'Coconut Oil'], 'MCT rich oil staple in Kerala cooking.'));
rawList.push(createRawRecord('I015', 'Sunflower oil', 'IFCT_2017', 'I015', 'ICMR-NIN IFCT 2017 Table I (Fats & Oils)', 'processed', 'Helianthus annuus', 'oils_fats', 'vegetable_oil', 'tbsp', 14, { energyKcal: 884, proteinG: 0, carbohydratesG: 0, fatG: 100.0, fiberG: 0, sugarG: 0, sodiumMg: 0, calciumMg: 0, ironMg: 0, potassiumMg: 0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Suriyakanthi Ennai', 'Sunflower Oil'], 'Refined cooking oil.'));
rawList.push(createRawRecord('USDA_171413', 'Olive oil, extra virgin', 'USDA_FDC', '171413', 'USDA FoodData Central SR Legacy', 'processed', 'Olea europaea', 'oils_fats', 'vegetable_oil', 'tbsp', 14, { energyKcal: 884, proteinG: 0, carbohydratesG: 0, fatG: 100.0, fiberG: 0, sugarG: 0, sodiumMg: 2.0, calciumMg: 1.0, ironMg: 0.56, potassiumMg: 1.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Extra Virgin Olive Oil', 'EVOO'], 'Monounsaturated fat olive oil.'));
rawList.push(createRawRecord('I020', 'Cow ghee', 'IFCT_2017', 'I020', 'ICMR-NIN IFCT 2017 Table I (Fats & Oils)', 'processed', 'Bos taurus', 'oils_fats', 'animal_fat', 'tbsp', 14, { energyKcal: 897, proteinG: 0, carbohydratesG: 0, fatG: 99.5, fiberG: 0, sugarG: 0, sodiumMg: 0, calciumMg: 3.0, ironMg: 0.02, potassiumMg: 1.0, vitaminAMcg: 800.0, vitaminCMg: 0, vitaminDMcg: 1.2, vitaminB12Mcg: 0, folateMcg: 0 }, ['Pasu Ney', 'Cow Ghee'], 'Aromatic cow ghee.'));
rawList.push(createRawRecord('I025', 'Butter, commercial', 'IFCT_2017', 'I025', 'ICMR-NIN IFCT 2017 Table I (Fats & Oils)', 'processed', 'Bos taurus', 'oils_fats', 'animal_fat', 'tbsp', 14, { energyKcal: 717, proteinG: 0.8, carbohydratesG: 0.1, fatG: 81.1, fiberG: 0, sugarG: 0.1, sodiumMg: 11.0, calciumMg: 24.0, ironMg: 0.02, potassiumMg: 24.0, vitaminAMcg: 684.0, vitaminCMg: 0, vitaminDMcg: 1.5, vitaminB12Mcg: 0.2, folateMcg: 3.0 }, ['Commercial Butter'], 'Commercial dairy fat.'));

// 11. SPICES & CONDIMENTS (18)
rawList.push(createRawRecord('J001', 'Ginger, fresh, raw', 'IFCT_2017', 'J001', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'fresh', 'Zingiber officinale', 'spices_condiments', 'rhizomes', 'g', 10, { energyKcal: 67, proteinG: 2.3, carbohydratesG: 12.3, fatG: 0.9, fiberG: 2.4, sugarG: 1.7, sodiumMg: 6.0, calciumMg: 20.0, ironMg: 1.4, potassiumMg: 320.0, vitaminAMcg: 0, vitaminCMg: 4.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 11.0 }, ['Inji', 'Adrak', 'Fresh Ginger'], 'Pungent rhizome staple in South Indian masala paste.'));
rawList.push(createRawRecord('J005', 'Garlic, fresh, raw', 'IFCT_2017', 'J005', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'fresh', 'Allium sativum', 'spices_condiments', 'bulbs', 'clove', 5, { energyKcal: 123, proteinG: 6.3, carbohydratesG: 24.0, fatG: 0.1, fiberG: 2.1, sugarG: 1.0, sodiumMg: 16.0, calciumMg: 30.0, ironMg: 1.2, potassiumMg: 400.0, vitaminAMcg: 0, vitaminCMg: 14.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 3.0 }, ['Poondu', 'Lahsun', 'Garlic Cloves'], 'Allicin rich spice bulb.'));
rawList.push(createRawRecord('J010', 'Green chilli, raw', 'IFCT_2017', 'J010', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'raw', 'Capsicum frutescens', 'spices_condiments', 'pods', 'piece', 5, { energyKcal: 30, proteinG: 2.9, carbohydratesG: 3.0, fatG: 0.6, fiberG: 6.8, sugarG: 1.8, sodiumMg: 7.0, calciumMg: 22.0, ironMg: 1.1, potassiumMg: 322.0, vitaminAMcg: 175.0, vitaminCMg: 111.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 23.0 }, ['Pachai Milagai', 'Hari Mirch', 'Green Chilli'], 'Pungent spice pod.'));
rawList.push(createRawRecord('J015', 'Red chilli powder, dry', 'IFCT_2017', 'J015', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Capsicum annuum', 'spices_condiments', 'powders', 'tsp', 3, { energyKcal: 236, proteinG: 15.0, carbohydratesG: 31.6, fatG: 6.2, fiberG: 34.8, sugarG: 7.2, sodiumMg: 26.0, calciumMg: 160.0, ironMg: 7.3, potassiumMg: 1950.0, vitaminAMcg: 765.0, vitaminCMg: 2.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 48.0 }, ['Milagai Thool', 'Lal Mirch Powder'], 'Ground red chilli spice powder.'));
rawList.push(createRawRecord('J020', 'Turmeric powder', 'IFCT_2017', 'J020', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Curcuma longa', 'spices_condiments', 'powders', 'tsp', 3, { energyKcal: 280, proteinG: 7.8, carbohydratesG: 64.9, fatG: 9.9, fiberG: 21.1, sugarG: 3.2, sodiumMg: 38.0, calciumMg: 182.0, ironMg: 41.4, potassiumMg: 2080.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 39.0 }, ['Manjal Thool', 'Haldi', 'Turmeric Powder'], 'Curcumin rich medicinal yellow powder.'));
rawList.push(createRawRecord('J025', 'Coriander seeds / powder', 'IFCT_2017', 'J025', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Coriandrum sativum', 'spices_condiments', 'seeds', 'tsp', 3, { energyKcal: 269, proteinG: 11.5, carbohydratesG: 22.6, fatG: 15.1, fiberG: 41.9, sugarG: null, sodiumMg: 35.0, calciumMg: 630.0, ironMg: 17.9, potassiumMg: 1267.0, vitaminAMcg: 157.0, vitaminCMg: 21.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: null }, ['Kothamalli Vithai', 'Dhania Powder'], 'Fragrant coriander seed spice.'));
rawList.push(createRawRecord('J030', 'Cumin seeds / Jeerakam', 'IFCT_2017', 'J030', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Cuminum cyminum', 'spices_condiments', 'seeds', 'tsp', 3, { energyKcal: 304, proteinG: 18.7, carbohydratesG: 17.4, fatG: 15.0, fiberG: 37.0, sugarG: 2.2, sodiumMg: 17.0, calciumMg: 931.0, ironMg: 31.0, potassiumMg: 1788.0, vitaminAMcg: 64.0, vitaminCMg: 7.7, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 10.0 }, ['Jeerakam', 'Jeera', 'Cumin Seeds'], 'Digestive seed used in Rasam and tempering.'));
rawList.push(createRawRecord('J035', 'Mustard seeds / Kadugu', 'IFCT_2017', 'J035', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Brassica nigra', 'spices_condiments', 'seeds', 'tsp', 3, { energyKcal: 508, proteinG: 20.0, carbohydratesG: 23.8, fatG: 39.7, fiberG: 12.2, sugarG: 6.8, sodiumMg: 13.0, calciumMg: 490.0, ironMg: 7.9, potassiumMg: 738.0, vitaminAMcg: 3.0, vitaminCMg: 7.1, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 162.0 }, ['Kadugu', 'Rai', 'Mustard Seeds'], 'Essential seed for South Indian Thali tempering (Tadka).'));
rawList.push(createRawRecord('J040', 'Black pepper / Milagu', 'IFCT_2017', 'J040', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Piper nigrum', 'spices_condiments', 'seeds', 'tsp', 3, { energyKcal: 217, proteinG: 10.9, carbohydratesG: 38.6, fatG: 2.5, fiberG: 26.5, sugarG: 0.6, sodiumMg: 20.0, calciumMg: 460.0, ironMg: 12.4, potassiumMg: 1329.0, vitaminAMcg: 27.0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 10.0 }, ['Milagu', 'Kali Mirch', 'Black Pepper Correns'], 'Piperine rich black pepper for Pongal and Rasam.'));
rawList.push(createRawRecord('J045', 'Curry leaves / Kariveppilai, fresh', 'IFCT_2017', 'J045', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'fresh', 'Murraya koenigii', 'spices_condiments', 'leaves', 'sprig', 2, { energyKcal: 97, proteinG: 6.1, carbohydratesG: 14.7, fatG: 1.0, fiberG: 6.4, sugarG: null, sodiumMg: 14.0, calciumMg: 830.0, ironMg: 0.9, potassiumMg: 600.0, vitaminAMcg: 7560.0, vitaminCMg: 4.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 94.0 }, ['Kariveppilai', 'Kadi Patta', 'Curry Leaves'], 'Aromatic leaves for all South Indian temperings.'));
rawList.push(createRawRecord('J050', 'Tamarind, pulp, raw', 'IFCT_2017', 'J050', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'raw', 'Tamarindus indica', 'spices_condiments', 'fruits', 'tbsp', 15, { energyKcal: 239, proteinG: 3.1, carbohydratesG: 56.5, fatG: 0.1, fiberG: 5.1, sugarG: 38.0, sodiumMg: 28.0, calciumMg: 170.0, ironMg: 1.3, potassiumMg: 628.0, vitaminAMcg: 2.0, vitaminCMg: 3.5, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 14.0 }, ['Puli', 'Imli', 'Tamarind Pulp'], 'Tart fruit pulp for Sambar, Rasam, and Puli Kuzhambu.'));
rawList.push(createRawRecord('J055', 'Scraped coconut, fresh', 'IFCT_2017', 'J055', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'fresh', 'Cocos nucifera', 'spices_condiments', 'kernel', 'tbsp', 15, { energyKcal: 354, proteinG: 3.3, carbohydratesG: 15.2, fatG: 33.5, fiberG: 9.0, sugarG: 6.2, sodiumMg: 20.0, calciumMg: 14.0, ironMg: 2.4, potassiumMg: 356.0, vitaminAMcg: 0, vitaminCMg: 3.3, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 26.0 }, ['Thengai Turuval', 'Nariyal', 'Fresh Grated Coconut'], 'Grated coconut for Chutney, Poriyal, and Kootu base.'));
rawList.push(createRawRecord('J060', 'Asafoetida / Perungayam', 'IFCT_2017', 'J060', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'processed', 'Ferula foetida', 'spices_condiments', 'resins', 'pinch', 1, { energyKcal: 297, proteinG: 4.0, carbohydratesG: 67.8, fatG: 1.1, fiberG: 4.1, sugarG: null, sodiumMg: 40.0, calciumMg: 690.0, ironMg: 39.0, potassiumMg: 1000.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: null }, ['Perungayam', 'Hing', 'Asafoetida'], 'Digestive resin spice for Sambar and Rasam.'));
rawList.push(createRawRecord('J065', 'Fenugreek seeds / Vendayam', 'IFCT_2017', 'J065', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Trigonella foenum-graecum', 'spices_condiments', 'seeds', 'tsp', 3, { energyKcal: 323, proteinG: 26.2, carbohydratesG: 44.1, fatG: 5.8, fiberG: 24.6, sugarG: null, sodiumMg: 67.0, calciumMg: 160.0, ironMg: 6.5, potassiumMg: 770.0, vitaminAMcg: 3.0, vitaminCMg: 3.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 57.0 }, ['Vendayam', 'Methi Seeds', 'Fenugreek'], 'Bitter seeds added to Idli batter and Vatha Kuzhambu.'));
rawList.push(createRawRecord('J070', 'Fennel seeds / Sombu', 'IFCT_2017', 'J070', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Foeniculum vulgare', 'spices_condiments', 'seeds', 'tsp', 3, { energyKcal: 345, proteinG: 15.8, carbohydratesG: 52.3, fatG: 14.9, fiberG: 39.8, sugarG: null, sodiumMg: 88.0, calciumMg: 1196.0, ironMg: 18.5, potassiumMg: 1694.0, vitaminAMcg: 13.0, vitaminCMg: 21.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: null }, ['Sombu', 'Saunf', 'Fennel Seeds'], 'Aromatic anise seed for Chettinad gravies and Biryani.'));
rawList.push(createRawRecord('J075', 'Cardamom, green / Elakkai', 'IFCT_2017', 'J075', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Elettaria cardamomum', 'spices_condiments', 'pods', 'pod', 1, { energyKcal: 311, proteinG: 10.8, carbohydratesG: 68.5, fatG: 6.7, fiberG: 28.0, sugarG: null, sodiumMg: 18.0, calciumMg: 383.0, ironMg: 14.0, potassiumMg: 1119.0, vitaminAMcg: 0, vitaminCMg: 21.0, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: null }, ['Elakkai', 'Elaichi', 'Green Cardamom'], 'Fragrant pod for Sweet Pongal and Payasam.'));
rawList.push(createRawRecord('J080', 'Cinnamon / Pattai', 'IFCT_2017', 'J080', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Cinnamomum verum', 'spices_condiments', 'bark', 'piece', 2, { energyKcal: 247, proteinG: 4.0, carbohydratesG: 80.6, fatG: 1.2, fiberG: 53.1, sugarG: 2.2, sodiumMg: 10.0, calciumMg: 1002.0, ironMg: 8.3, potassiumMg: 431.0, vitaminAMcg: 15.0, vitaminCMg: 3.8, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 6.0 }, ['Pattai', 'Dalchini', 'Cinnamon Bark'], 'Aromatic bark for Biryani masala.'));
rawList.push(createRawRecord('J085', 'Cloves / Grambu', 'IFCT_2017', 'J085', 'ICMR-NIN IFCT 2017 Table J (Spices)', 'dried', 'Syzygium aromaticum', 'spices_condiments', 'buds', 'piece', 1, { energyKcal: 274, proteinG: 6.0, carbohydratesG: 65.5, fatG: 13.0, fiberG: 33.9, sugarG: 2.4, sodiumMg: 277.0, calciumMg: 632.0, ironMg: 11.8, potassiumMg: 1020.0, vitaminAMcg: 8.0, vitaminCMg: 0.2, vitaminDMcg: null, vitaminB12Mcg: null, folateMcg: 68.0 }, ['Grambu', 'Laung', 'Cloves'], 'Pungent spice flower buds.'));

// 12. BASIC INGREDIENTS (3)
rawList.push(createRawRecord('K001', 'Sugar, refined white', 'IFCT_2017', 'K001', 'ICMR-NIN IFCT 2017 Table K (Sugars & Sweets)', 'processed', null, 'basic_ingredients', 'sweeteners', 'tsp', 5, { energyKcal: 398, proteinG: 0, carbohydratesG: 99.4, fatG: 0, fiberG: 0, sugarG: 99.4, sodiumMg: 0, calciumMg: 1.0, ironMg: 0.1, potassiumMg: 2.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Sarkarai', 'Chini', 'White Sugar'], 'Refined granulated sucrose sugar.'));
rawList.push(createRawRecord('K005', 'Jaggery, cane / Vellam', 'IFCT_2017', 'K005', 'ICMR-NIN IFCT 2017 Table K (Sugars & Sweets)', 'processed', 'Saccharum officinarum', 'basic_ingredients', 'sweeteners', 'tbsp', 15, { energyKcal: 383, proteinG: 0.4, carbohydratesG: 95.0, fatG: 0.1, fiberG: 0, sugarG: 85.0, sodiumMg: 30.0, calciumMg: 80.0, ironMg: 2.6, potassiumMg: 1050.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Vellam', 'Gur', 'Cane Jaggery'], 'Unrefined cane sugar jaggery for Sweet Pongal and Payasam.'));
rawList.push(createRawRecord('K010', 'Table salt / Sodium chloride', 'IFCT_2017', 'K010', 'ICMR-NIN IFCT 2017 Table K (Salts & Minerals)', 'processed', 'Sodium chloride', 'basic_ingredients', 'minerals', 'tsp', 6, { energyKcal: 0, proteinG: 0, carbohydratesG: 0, fatG: 0, fiberG: 0, sugarG: 0, sodiumMg: 38758.0, calciumMg: 24.0, ironMg: 0.3, potassiumMg: 8.0, vitaminAMcg: 0, vitaminCMg: 0, vitaminDMcg: 0, vitaminB12Mcg: 0, folateMcg: 0 }, ['Uppu', 'Namak', 'Table Salt'], 'Refined iodized table salt.'));

// Generate Normalized Records
const gaugeList = rawList.map(normalizeRecord);

// Write to data/foods.raw.json and data/foods.gauge.json
const rawPath = path.join(__dirname, '../data/foods.raw.json');
const gaugePath = path.join(__dirname, '../data/foods.gauge.json');

fs.writeFileSync(rawPath, JSON.stringify(rawList, null, 2), 'utf-8');
fs.writeFileSync(gaugePath, JSON.stringify(gaugeList, null, 2), 'utf-8');

console.log(`Successfully generated:`);
console.log(`- ${rawPath} (${rawList.length} items)`);
console.log(`- ${gaugePath} (${gaugeList.length} items)`);
